import {
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  UpIcon,
  DownIcon,
  GoodIcon,
  BadIcon,
  WarningFilledIcon,
  WarningOutlineIcon,
  CalendarIcon,
  WaterdropIcon,
  ToiletIcon,
  ThermometerIcon,
  HeartbeatIcon,
  SparkIcon,
  TwoPanelIcon,
  LockIcon,
  RecordIcon,
  ReportIcon,
  PlusIcon,
  SearchIcon,
  EditIcon,
  ResetIcon,
  DownloadIcon,
  CircleCheckIcon,
  FullLogo32Icon,
  FullLogo40Icon,
  SmallLogoIcon,
  ElderIcon,
  WorkerIcon,
  HealthIcon,
  MealIcon,
  StampGoodIcon,
  StampBadIcon,
  BrainIcon,
  ActivityIcon,
  LocationIcon,
  TransportationIcon,
  BlockIcon,
  CheckedIcon,
  UncheckedIcon,
  PlusBoxIcon,
  MinusBoxIcon,
  DeleteIcon,
  PhotoAlternateIcon,
  PhotoDeleteButtonIcon,
  AddPhotoIcon,
  AddPhotoByCameraIcon,
  AlarmIcon,
  AlignUpIcon,
  AlignDownIcon,
  AlertNotFoundIcon,
} from "@/assets";

export const defaultIconSize = 16;

// 하단은 아이콘 이름과 아이콘 컴포넌트를 매핑한 객체입니다.
// 아이콘 이름은 아이콘 컴포넌트의 이름과 동일합니다.
export const iconMap = {
  arrowUp: ArrowUpIcon,
  arrowDown: ArrowDownIcon,
  arrowRight: ArrowRightIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronDown: ChevronDownIcon,
  up: UpIcon,
  down: DownIcon,
  good: GoodIcon,
  bad: BadIcon,
  warningFilled: WarningFilledIcon,
  warningOutline: WarningOutlineIcon,
  calendar: CalendarIcon,
  waterdrop: WaterdropIcon,
  toilet: ToiletIcon,
  thermometer: ThermometerIcon,
  heartbeat: HeartbeatIcon,
  spark: SparkIcon,
  twoPanel: TwoPanelIcon,
  lock: LockIcon,
  record: RecordIcon,
  report: ReportIcon,
  plus: PlusIcon,
  search: SearchIcon,
  edit: EditIcon,
  reset: ResetIcon,
  download: DownloadIcon,
  circleCheck: CircleCheckIcon,
  fullLogo32: FullLogo32Icon,
  fullLogo40: FullLogo40Icon,
  smallLogo: SmallLogoIcon,
  elder: ElderIcon,
  worker: WorkerIcon,
  health: HealthIcon,
  meal: MealIcon,
  stampGood: StampGoodIcon,
  stampBad: StampBadIcon,
  brain: BrainIcon,
  activity: ActivityIcon,
  location: LocationIcon,
  transportation: TransportationIcon,
  block: BlockIcon,
  checked: CheckedIcon,
  unchecked: UncheckedIcon,
  plusBox: PlusBoxIcon,
  minusBox: MinusBoxIcon,
  delete: DeleteIcon,
  photoAlternate: PhotoAlternateIcon,
  photoDeleteButton: PhotoDeleteButtonIcon,
  addPhoto: AddPhotoIcon,
  addPhotoByCamera: AddPhotoByCameraIcon,
  alarm: AlarmIcon,
  alignUp: AlignUpIcon,
  alignDown: AlignDownIcon,
  alertNotFound: AlertNotFoundIcon,
};
