// API 형태의 더미 데이터
export const API_ELDER_DUMMY_DATA = {
  status: 0,
  message: "성공",
  result: [
    {
      name: "김수진",
      gender: "FEMALE" as const,
      birthDate: "1945-03-15",
      careLevel: 1,
      avatarUrl: "https://cdn.example.com/avatar/USR001.png",
      careNumber: "AA12345678",
      guardianName: "김영희",
      guardianRelation: "딸",
      guardianRelationBirthDate: "1975-08-20",
      guardianPhoneNumber: "010-1234-5678",
      guardianAvatarUrl: "https://cdn.example.com/avatar/GUARD001.png",
      isSubscribed: true,
    },
    {
      name: "박영수",
      gender: "MALE" as const,
      birthDate: "1950-07-22",
      careLevel: 2,
      avatarUrl: "https://cdn.example.com/avatar/USR002.png",
      careNumber: "BB87654321",
      guardianName: "박정민",
      guardianRelation: "아들",
      guardianRelationBirthDate: "1980-12-10",
      guardianPhoneNumber: "010-8765-4321",
      guardianAvatarUrl: "https://cdn.example.com/avatar/GUARD002.png",
      isSubscribed: false,
    },
    {
      name: "이미경",
      gender: "FEMALE" as const,
      birthDate: "1948-11-08",
      careLevel: 3,
      avatarUrl: "https://cdn.example.com/avatar/USR003.png",
      careNumber: "CC11223344",
      guardianName: "이상훈",
      guardianRelation: "아들",
      guardianRelationBirthDate: "1978-05-15",
      guardianPhoneNumber: "010-1122-3344",
      guardianAvatarUrl: "https://cdn.example.com/avatar/GUARD003.png",
      isSubscribed: true,
    },
    {
      name: "최철수",
      gender: "MALE" as const,
      birthDate: "1952-01-30",
      careLevel: 4,
      avatarUrl: "https://cdn.example.com/avatar/USR004.png",
      careNumber: "DD55667788",
      guardianName: "최민정",
      guardianRelation: "딸",
      guardianRelationBirthDate: "1982-03-25",
      guardianPhoneNumber: "010-5566-7788",
      guardianAvatarUrl: "https://cdn.example.com/avatar/GUARD004.png",
      isSubscribed: true,
    },
    {
      name: "홍노인",
      gender: "MALE" as const,
      birthDate: "1950-05-12",
      careLevel: 5,
      avatarUrl: "https://cdn.example.com/avatar/USR123.png",
      careNumber: "AA1234567",
      guardianName: "이보호자",
      guardianRelation: "딸",
      guardianRelationBirthDate: "1978-10-02",
      guardianPhoneNumber: "010-1234-5678",
      guardianAvatarUrl: "https://cdn.example.com/avatar/GUARD123.png",
      isSubscribed: true,
    },
  ],
};
